### ISSUE TITLE
Bad description of Sources for Android SDK on the website

### ISSUE THREAD

**Issue by ouattararomuald** [hariadi/viewer#53]
Hi,
The description for the section [**Sources for Android SDK**](http://ady.my/viewer/source/) is the same as for [**Tool**](http://ady.my/viewer/tool/).

**Sources for Android SDK**
------------------------------------
> Contains tools for debugging and testing, plus other utilities that are required to develop an app. If you've just installed the SDK starter package, then you already have the latest version of this package. Make sure you keep this up to date.

**Tool**
------------------------------------
> Contains tools for debugging and testing, plus other utilities that are required to develop an app. If you've just installed the SDK starter package, then you already have the latest version of this package. Make sure you keep this up to date.

The description of **Sources for Android SDK** should be changed.

**Comment by hariadi** [comment]
Good catch.Thanks!
